### ISSUE TITLE
Remove redundant test API

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/cmd-forwarder-sriov#14]
## Motivation

https://github.com/networkservicemesh/cmd-forwarder-sriov/blob/master/test/tools/channel.go

It looks like `test/tools/channel` actually is not needed because all selects can be used inside the test as we do this mostly in each of our SDK tests. 

NOTE: Using `select` in the test is a natural approach for golang.

**Comment by Bolodya1997** [comment]
Yep, removed.

**Comment by denis-tingaikin** [comment]
@Bolodya1997 Nice! let's add a link to PR and close thins
