### ISSUE TITLE
Testing application test/applications/k8s can be removed

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/cmd-forwarder-sriov#16]
Actually application https://github.com/networkservicemesh/cmd-forwarder-sriov/blob/master/test/applications/k8s/main.go can be removed.

## Motivation

We can use a stub of k8s/kubeadm server and use the real cmd-forwarder-sriov application. In this case, we'll test the real application. Currently, we are testing some testing stub...

**Comment by Bolodya1997** [comment]
Application has been removed, but we still using some test GRPC servers implementing kubelet API. But I don't think that it is an issue because it is only needed for docker testing. Real application is really tested under integration tests.

**Comment by denis-tingaikin** [comment]
@Bolodya1997 I think it is ok. My point was related to an additional application that should not be located in cmd-* repo.
