### ISSUE TITLE
move device plugin server into common repo

### ISSUE THREAD

**Issue by pperiyasamy** [networkservicemesh/cmd-forwarder-sriov#163]
Can we move device plugin server [implementation](https://github.com/networkservicemesh/cmd-forwarder-sriov/blob/main/internal/deviceplugin/server.go) into a common repo like sdk-k8s or sdk-sriov so that it can also be reused by ovs forwarder (going to get implemented) that has support for smartnic based VFs.
The forwarder just have to rely this [StartServers API ](https://github.com/networkservicemesh/cmd-forwarder-sriov/blob/main/internal/deviceplugin/server.go#L59)to start the device plugin server with required token pools based on the sriov.conf file.

**Comment by denis-tingaikin** [comment]
Related to https://github.com/networkservicemesh/cmd-forwarder-sriov/blob/main/internal/deviceplugin/server.go

As I can see it has dep on "github.com/networkservicemesh/sdk-sriov/pkg/tools/tokens"

Actually, the dep is using only for https://github.com/networkservicemesh/cmd-forwarder-sriov/blob/main/internal/deviceplugin/server.go#L268

So to remove the dependency on sdk-sriov I would be suggesting just adding the method `ToEnv` into https://github.com/networkservicemesh/cmd-forwarder-sriov/blob/main/internal/deviceplugin/server.go#L37.

Then deviceplugin server can be moved into sdk-k8s and can be reusable :slightly_smiling_face: (ed

**Comment by denis-tingaikin** [comment]
Summons @Bolodya1997

**Comment by Bolodya1997** [comment]
I am not looking forward to separate `ToEnv` and `FromEnv` methods to different repos, but I suppose that we can move whole `tokens` package to `sdk` tools, because it doesn't have any dependencies on some SR-IOV specific stuff.
After that we definitely can move `deviceplugin` to the `sdk-k8s`.
