### ISSUE TITLE
Move all tests to separate testing pkg

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/cmd-forwarder-sriov#17]
## Motivation

We are not using white-box testing in newly styled NSM repositories. So then we should move all tests to separate pkgs and make sure that we are not testing private states

https://github.com/networkservicemesh/cmd-forwarder-sriov/blob/master/local/sdk-sriov/pkg/k8s/manager_test.go#L17

**Comment by Bolodya1997** [comment]
Fixed.

**Comment by denis-tingaikin** [comment]
@Bolodya1997 Nice! Let's attach a link to PR and this one can be closed
