### ISSUE TITLE
Add initial CI for cmd-forwarder-sriov repository

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/cmd-forwarder-sriov#2]

**Comment by denis-tingajkin** [comment]
You can just copy these files for example https://github.com/networkservicemesh/cmd-forwarder-vppagent/tree/master/.github/workflows

**Comment by edwarnicke** [comment]
> You can just copy these files for example https://github.com/networkservicemesh/cmd-forwarder-vppagent/tree/master/.github/workflows into `.github/workflows` dir.

Do look through those files for the string 'cmd-forwarder-vppagent' which you would need to replace :)
