### ISSUE TITLE
Add VF selector chain element

### ISSUE THREAD

**Issue by lvfxx** [networkservicemesh/cmd-forwarder-sriov#8]
Add chain element that will select one from virtual functions across all available NICs based on next info:
1) Returned `endpointPortMacAddress` returned by eNSMgr in `NetworkServiceRequest.MechanismPreferences.Parameters` map
2) Forwarder config, containing info about which PF is connected to which server port 
3) list of VFs associated with each PF

This chain element has to add `vfInterfaceName` parameter containing interface name to  `NetworkServiceRequest.MechanismPreferences.Parameters` map

**Comment by Bolodya1997** [comment]
Forwarder is ready, no more need.

**Comment by denis-tingaikin** [comment]
Closing via https://github.com/networkservicemesh/cmd-forwarder-sriov/issues/8#issuecomment-762051897
